# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  checkout-project:
    steps:
      - checkout:
          path: ~/project

  restore-cache:
    steps:
      - restore_cache:
          keys:
            - packages-{{ checksum "~/project/package-lock.json" }}
  save-cache:
    steps:
      - save_cache:
          paths:
            - ~/project/node_modules
          key: packages-{{ checksum "~/project/package-lock.json" }}

  install:
    description: "Run the installation process"
    steps:
      - run: npm install

  test:
    description: "Run the tests"
    steps:
      - run: npm run test-ci
      - store_artifacts:
          path: coverage

executors:
  node-container:
    docker:
      - image: cimg/node:16.14.0
        environment:
          NODE_ENV: development
    working_directory: ~/project

jobs:
  test:
    executor: node-container
    steps:
      - checkout-project
      - restore-cache
      - install
      - save-cache
      - test

workflows:
  build-function:
    jobs:
      - test
